### ISSUE TITLE
delimiter for splitting path for mac

### ISSUE THREAD

**Issue by minoue-xx** [HppyCtrlEngnrng/MATLABle#1]
I would suggest including colon for macOS in addition to semi-colon for PC.

> path_list = string(split(path, {';',':'}));

**Comment by HppyCtrlEngnrng** [comment]
Thank you very much for your suggestion!
I found that splitting by ':' breaks Windows style path led by drive letters, such as C:, D:.
So I would implement your suggestion with os check by ispc().

`    if ispc()
        path_list = string(split(path, ';'));
    else
        path_list = string(split(path, ':'));
    end`

**Comment by minoue-xx** [comment]
Thank you :)
